/* PRODUCT */
export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCTS_FAIL = "GET_PRODUCT_FAIL"

/* PRODUCT DETAIL*/
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL"
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS"
export const GET_PRODUCT_DETAIL_FAIL = "GET_PRODUCT_DETAIL_FAIL"

/**
 * add PRODUCT
 */
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL"

/**
 * Edit PRODUCT
 */
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"

/**
 * Delete PRODUCT
 */
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"

/**
 * Action Status
 */
export const CONFIRM_VS_ACTION_SUCCESS = "CONFIRM_VS_ACTION_SUCCESS"
export const CONFIRM_VS_ACTION_FAIL = "CONFIRM_VS_ACTION_FAIL"

/**
 * Search Product
 */
export const SEARCH_PRODUCT = "SEARCH_PRODUCT"
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS"
export const SEARCH_PRODUCT_FAIL = "SEARCH_PRODUCT_FAIL"

/**
 * Unload Product
 */
export const PRODUCT_UNLOAD = "PRODUCT_UNLOAD"
export const PRODUCT_UNLOAD_SUCCESS = "PRODUCT_UNLOAD_SUCCESS"
export const PRODUCT_UNLOAD_FAIL = "PRODUCT_UNLOAD_FAIL"

export const PRODUCT_REINIT = "PRODUCT_REINIT"
